### ISSUE TITLE
SQL Server Product and Version Reporting with SCCM

### ISSUE THREAD

**Issue by ramg1967** [MEM-Zone/sccm-zone.com#17]
Hi - When, I run the report, I get this error.  I have full access to DB.  Do, I need to change any permission within the DB?

Error Message:
An error has occurred during report processing. (rsProcessingAborted)
Query execution failed for dataset 'AdminID'. (rsErrorExecutingCommand)
Cannot find either column "dbo" or the user-defined function or aggregate "dbo.fn_rbac_GetAdminIDsfromUserSIDs", or the name is ambiguous.

**Comment by svillama** [comment]
Hi - I got this error. 
Microsoft.Reporting.WinForms.ReportServerException
An error has occurred during report processing. (rsProcessingAborted)


Stack Trace:
   at Microsoft.Reporting.WinForms.ServerReport.ServerUrlRequest(Boolean isAbortable, String url, Stream outputStream, String& mimeType, String& fileNameExtension)
   at Microsoft.Reporting.WinForms.ServerReport.InternalRender(Boolean isAbortable, String format, String deviceInfo, NameValueCollection urlAccessParameters, Stream reportStream, String& mimeType, String& fileNameExtension)
   at Microsoft.Reporting.WinForms.AsyncMainStreamRenderingOperation.RenderServerReport(ServerReport report)
   at Microsoft.Reporting.WinForms.AsyncRenderingOperation.PerformOperation()
   at Microsoft.Reporting.WinForms.ReportViewer.AsyncReportOperationWrapper.PerformOperation()
   at Microsoft.Reporting.WinForms.ProcessingThread.ProcessThreadMain(Object arg)

-------------------------------

Microsoft.Reporting.WinForms.ReportServerException
Query execution failed for dataset 'SQLProductInfo'. (rsErrorExecutingCommand)


Stack Trace:
   at Microsoft.Reporting.WinForms.ServerReport.ServerUrlRequest(Boolean isAbortable, String url, Stream outputStream, String& mimeType, String& fileNameExtension)
   at Microsoft.Reporting.WinForms.ServerReport.InternalRender(Boolean isAbortable, String format, String deviceInfo, NameValueCollection urlAccessParameters, Stream reportStream, String& mimeType, String& fileNameExtension)
   at Microsoft.Reporting.WinForms.AsyncMainStreamRenderingOperation.RenderServerReport(ServerReport report)
   at Microsoft.Reporting.WinForms.AsyncRenderingOperation.PerformOperation()
   at Microsoft.Reporting.WinForms.ReportViewer.AsyncReportOperationWrapper.PerformOperation()
   at Microsoft.Reporting.WinForms.ProcessingThread.ProcessThreadMain(Object arg)

-------------------------------

Microsoft.Reporting.WinForms.ReportServerException
For more information about this error navigate to the report server on the local server machine, or enable remote errors


Stack Trace:
   at Microsoft.Reporting.WinForms.ServerReport.ServerUrlRequest(Boolean isAbortable, String url, Stream outputStream, String& mimeType, String& fileNameExtension)
   at Microsoft.Reporting.WinForms.ServerReport.InternalRender(Boolean isAbortable, String format, String deviceInfo, NameValueCollection urlAccessParameters, Stream reportStream, String& mimeType, String& fileNameExtension)
   at Microsoft.Reporting.WinForms.AsyncMainStreamRenderingOperation.RenderServerReport(ServerReport report)
   at Microsoft.Reporting.WinForms.AsyncRenderingOperation.PerformOperation()
   at Microsoft.Reporting.WinForms.ReportViewer.AsyncReportOperationWrapper.PerformOperation()
   at Microsoft.Reporting.WinForms.ProcessingThread.ProcessThreadMain(Object arg)

-------------------------------

**Comment by Ioan-Popovici** [comment]
@Svillama please use the newest version of the report v2.6.5. The extension and definitions for version v2.6.4 were not tested and were incorrect.
I’ve updated the definitions, extensions and report today.

**Comment by Ioan-Popovici** [comment]
@ramg1967 What version of SCCM are you using? The "dbo.fn_rbac_GetAdminIDsfromUserSIDs" is an essential function and it's available from SCCM 2012 R2

**Comment by ramg1967** [comment]
@Ioan-Popovici - CB1910

**Comment by Ioan-Popovici** [comment]
@ramg1967 
Modify the code below at 'YOUR_SITE_CODE' with your site code, run it in SSMS (SQL Server Management Studio) and post the results here.

```SQL
USE CM_YOUR_SITE_CODE
SELECT *
	FROM    dbo.sysobjects
	WHERE   id = OBJECT_ID(N'[dbo].[fn_rbac_GetAdminIDsfromUserSIDs]')
```

**Comment by ramg1967** [comment]
Query completed successfully.
fn_rbac_GetAdminIDsfromUserSIDs	709681676	FN	1	0	0	0	0	0	2019-01-06 16:25:24.457	0	0	0	FN	0	0	0	2019-01-06 16:25:24.457	0	0	0	0	0	0	0

**Comment by Ioan-Popovici** [comment]
Are any of the pre-installed reports working? All of them use this function in this exact form.

**Comment by ramg1967** [comment]
Here is pre installed report from CB1910.

[cid:image001.png@01D60695.946C7D40]

Thanks

Ram

WWW.INFOTECHRAM.COM<http://WWW.INFOTECHRAM.COM>

**Comment by Ioan-Popovici** [comment]
I can't see the image but I presume it's working.

Is the CM_DB SQL server different from the SSRS DB Server?

**Comment by Ioan-Popovici** [comment]
Please join this discord server it's easier to communicate
https://discord.gg/PWwVMe

**Comment by Ioan-Popovici** [comment]
Closing due inactivity, please reopen if you have more info
